### PR TITLE
Large amount of updates to the language

### PR DESCRIPTION
**Pull request by vihangm**
This adds a lot more complexity to the language in an effort to improve coloring. Here's a preview.
proto

P.S. Not sure if you want to continue maintaining the repo. Let me know what you'd prefer,

### CODE REVIEW

**Comment by awalterschulze** [comment]
This looks amazing :D
I would love it if you would like to take over maintaining this repo?

**Comment by awalterschulze** [comment]
Are you interested?

**Comment by vihangm** [comment]
Sure

**Comment by awalterschulze** [comment]
Ok great :)

So the first you should do is fork
https://github.com/wbond/package_control_channel
and change this line to point to your repo link
https://github.com/wbond/package_control_channel/blob/master/repository/p.json#L1426

What do you think?

**Comment by awalterschulze** [comment]
Maybe these instructions will help
https://packagecontrol.io/docs/renaming_a_package

**Comment by awalterschulze** [comment]
Point me to your pull request of package control so I can also say that it is ok to change it to point away from my repo.  Does that make sense?

**Comment by awalterschulze** [comment]
Excellent.
I see it has been merged on sublime package control :)
Now I should probably delete my repo or make a readme.md that points back to your repo.
I would like your repo not to have the "forked from" link, because I think the link will confuse people.
What would you prefer?

**Comment by vihangm** [comment]
According to [this](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository) if you delete the repo, one of the forks will become the new parent.
It doesn't say what mechanism is used to decide which one though.

I'm fine with whatever method you choose.

**Comment by awalterschulze** [comment]
I am contacting a human at github.
They are usually very responsive and helpful.

**Comment by vihangm** [comment]
Looks like we're all set.

**Comment by awalterschulze** [comment]
yeah github responded and made you the root. I love this place :-)

**Pull request closed without merging**
